MekanikPenguin/UnrealBnB

README.md

Coucou lead dev voilà un petit readme

readme modif

---

app/controllers/bookings_controller.rb
app/controllers/offers_controller.rb

Voici les controllers Offers et Bookings

Offers and Bookings Controllers

---

app/controllers/pages_controller.rb
app/views/bookings/index.html.erb
app/views/bookings/show.html.erb
app/views/layouts/application.html.erb
app/views/offers/edit.html.erb
app/views/offers/index.html.erb
app/views/offers/new.html.erb
app/views/offers/show.html.erb

Basic views html

---

app/models/booking.rb
app/models/offer.rb

-Ajout commentaires pour organisation du code 
-Validations presence ajouté sur model booking et offer

Models validations

---

app/views/layouts/_footer.html.erb
app/views/layouts/_navbar.html.erb
app/views/layouts/_notice.html.erb
app/views/layouts/_searchbar.html.erb
app/views/layouts/application.html.erb

New organisation of application
Have to replace css too

replaced code by renders

---

app/assets/stylesheets/application.scss

léger margin-left sur les cards que j'ai enlevé

fixing margin of .card-text class

---

app/controllers/application_controller.rb
app/controllers/offers_controller.rb
app/controllers/pages_controller.rb
app/views/devise/registrations/new.html.erb
app/views/layouts/_navbar.html.erb

-Réglé : Before process_action callback :authenticate_user! has not been defined
-Changé le code par défaut du new-offer pour reprendre l'id du user connecté
-Navbar réactive à la connexion du user
-Formulaire de registration complet
-Possibilité de log out

User authorisation

---

app/assets/stylesheets/application.scss
app/views/offers/show.html.erb

Ajout du html et CSS pour la page show

Offer Show

---

Gemfile.lock
app/views/offers/show.html.erb

page-offer-show 2

---

app/controllers/bookings_controller.rb
app/javascript/controllers/datepicker_controller.js
app/models/offer.rb
app/views/offers/show.html.erb
config/importmap.rb
config/routes.rb

flatpicker done

---

db/seeds.rb

NEED TO DROP CREATE MIGRATE SEED

Page offer show booking

---

app/controllers/bookings_controller.rb
app/controllers/offers_controller.rb
app/models/user.rb
app/views/pages/mybookings.html.erb
app/views/pages/myoffers.html.erb

My bookings

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_cards.scss
app/views/offers/index.html.erb

ajout d'une box shadow, border radius, l'username en tant qu'hôte , ajour de l'icon coin

styling card

---

app/views/pages/myoffers.html.erb

resolved images in myoffers

---

app/javascript/controllers/address_autocomplete_controller.js
app/javascript/controllers/map_controller.js
app/views/offers/_form.html.erb

Adding Search function for Map

---

app/views/offers/index.html.erb
app/views/pages/mybookings.html.erb
app/views/pages/myoffers.html.erb

adding bold on titles and fixing edentation

---

Gemfile
Gemfile.lock
app/controllers/offers_controller.rb
app/models/offer.rb
app/views/layouts/_searchbar.html.erb

ajout de ligne de code pour la fonctionnalité Seach. 
fichier modifié : offer.rb, offers_controller

ajout de la fonctionnalité search

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/offers/_form.html.erb
app/views/offers/index.html.erb
app/views/pages/myoffers.html.erb

Css fixing issues

---

app/controllers/bookings_controller.rb
app/controllers/offers_controller.rb
app/models/booking.rb
app/views/pages/mybookings.html.erb
app/views/pages/myoffers.html.erb
config/routes.rb
db/migrate/20240815092410_add_status_to_bookings.rb
db/schema.rb

Ajout de la fonctionnalité Réservation En attente / Acceptée / Refusée

Improve my bookings

---

app/views/pages/mybookings.html.erb

mybookings cards

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_icon.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_map.scss
app/assets/stylesheets/components/_navbar.scss

classes scss rangées

---

app/assets/stylesheets/application.scss
app/views/offers/show.html.erb
app/views/pages/mybookings.html.erb

enhancing the booking alert messages

---

app/assets/stylesheets/application.scss
app/views/offers/show.html.erb
app/views/pages/myoffers.html.erb

SHOW optimisation

---

app/views/pages/myoffers.html.erb

new avatar face and hr balises added

myoffers page optimised

---

app/views/offers/show.html.erb

rating offer wasn't added
